CREATE TABLE users(
	user_id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
	username        VARCHAR(50) NOT NULL,
	password        VARCHAR(500) NOT NULL,
	CONSTRAINT pk_users PRIMARY KEY (user_id)
);

CREATE TABLE roles(
	role_id BIGINT  GENERATED BY DEFAULT AS IDENTITY,
	role_name       VARCHAR(50),
	description     VARCHAR(100),
	user_id         BIGINT      NOT NULL,
	CONSTRAINT pk_roles PRIMARY KEY (role_id),
	CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(user_id)
);

CREATE TABLE product_notes (
    note_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ext_prod_id   BIGINT        NOT NULL,
    note_content  VARCHAR(1000) NOT NULL,
    created_by    VARCHAR(255)  NOT NULL,
    updated_at    TIMESTAMP(6),
    CONSTRAINT pk_product_notes PRIMARY KEY (note_id),
    CONSTRAINT uq_product_notes_ext_prod_id UNIQUE (ext_prod_id),
    CONSTRAINT ck_product_notes_note_not_blank CHECK (length(btrim(note_content)) > 0),
    CONSTRAINT ck_product_notes_created_by_not_blank CHECK (length(btrim(created_by)) > 0)
);

CREATE TABLE audit_logs (
    audit_log_id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    endpoint_url      VARCHAR(255) NOT NULL,
    http_method       VARCHAR(10)  NOT NULL,
    status_response   VARCHAR(20)  NOT NULL,
    response_time_ms  BIGINT       NOT NULL,
    "timestamp"       TIMESTAMP(6) NOT NULL,
    error_message     VARCHAR(500),

    CONSTRAINT pk_audit_logs PRIMARY KEY (audit_log_id),
    CONSTRAINT ck_audit_logs_response_time_non_negative CHECK (response_time_ms >= 0),
    CONSTRAINT ck_audit_logs_http_method CHECK (
        http_method IN ('GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS', 'TRACE')
    )
);

CREATE INDEX idx_audit_logs_timestamp ON audit_logs ("timestamp" DESC);
CREATE INDEX idx_audit_logs_endpoint_url ON audit_logs (endpoint_url);
