CREATE TABLE users(
	user_id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
	username        VARCHAR(50) NOT NULL,
	password        VARCHAR(500) NOT NULL,
	CONSTRAINT pk_users PRIMARY KEY (user_id)
);

CREATE TABLE roles(
	role_id BIGINT  GENERATED BY DEFAULT AS IDENTITY,
	role_name       VARCHAR(50),
	description     VARCHAR(100),
	user_id         BIGINT      NOT NULL,
	CONSTRAINT pk_roles PRIMARY KEY (role_id),
	CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(user_id)
);

CREATE TABLE product_notes (
    note_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ext_prod_id   BIGINT        NOT NULL,
    note_content  VARCHAR(1000) NOT NULL,
    created_by    VARCHAR(255)  NOT NULL,
    updated_at    TIMESTAMP(6),
    CONSTRAINT pk_product_notes PRIMARY KEY (note_id),
    CONSTRAINT uq_product_notes_ext_prod_id UNIQUE (ext_prod_id),
    CONSTRAINT ck_product_notes_note_not_blank CHECK (length(btrim(note_content)) > 0),
    CONSTRAINT ck_product_notes_created_by_not_blank CHECK (length(btrim(created_by)) > 0)
);

CREATE TABLE audit_logs (
    audit_log_id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    operation_type    VARCHAR(100) NOT NULL,
    status            VARCHAR(20)  NOT NULL,
    duration_ms       BIGINT       NOT NULL,
    regis_date        TIMESTAMP(6) NOT NULL,
    created_by        VARCHAR(50)  NOT NULL,
    error             VARCHAR(500),
    CONSTRAINT pk_audit_logs PRIMARY KEY (audit_log_id),
    CONSTRAINT ck_audit_logs_duration_non_negative CHECK (duration_ms >= 0),
    CONSTRAINT ck_audit_logs_status CHECK (
        status IN ('SUCCESS', 'FAILED')
    )
);

CREATE INDEX idx_audit_logs_regis_date ON audit_logs (regis_date DESC);
CREATE INDEX idx_audit_logs_operation_type ON audit_logs (operation_type);
