spring:
  application:
    name: ecommerce_catalog
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
      open-in-view: false

resilience4j:
  retry:
    instances:
      fakeStore:
        maxAttempts: 3
        waitDuration: 2s
        # retryExceptions:
        #   - org.springframework.web.client.ResourceAccessException

  circuitbreaker:
    instances:
      fakeStore:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        slowCallRateThreshold: 75
        slowCallDurationThreshold: 3s
        waitDurationInOpenState: 15s
        permittedNumberOfCallsInHalfOpenState: 3

security:
  jwt:
    issuer: "ecommerce-api"
    expiration: 900
    secret: ${JWT_SECRET}

external:
  api:
    fake-store:
      url: ${API_FAKE_STORE_URL}
